version: 2

sources:
  - name: raw_data
    database: analytical-engineering-04   # BigQuery project ID
    schema: prod                          # BigQuery dataset name
    tables:
      - name: yellow_tripdata
        identifier: yellow_tripdata
      - name: green_tripdata
        identifier: green_tripdata
      - name: fhv_tripdata
        identifier: fhv_tripdata
      - name: fhvhv_tripdata
        identifier: fhvhv_tripdata
      - name: taxi_zone_lookup
        identifier: taxi_zone_lookup
